apiVersion: apps/v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apache
  name: apache
spec:
  containers:
    - image: larian147/apacheimg:v1
      name: apachepod
      ports:
        - containerPort: 80
      resources: {}
      volumeMounts:
        - name: config-volume
          mountPath: /site/
  volumes:
    - name: config-volume
      configMap:
        name: apache-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: apache-config
data:
  congigmap.yaml: |
    sudo sh -c "cd /var/lib/docker/ && <command>"
  pot.yaml: |
    apiVersion: apps/v1
    kind: Pod
