apiVersion: apps/v1
kind: Pod
metadata:
  creationTimestamp: null
  name: apache
  labels:
    run: apache
  name: apache
spec:
  containers:
    - image: larian147/apacheimg:v1
      name: apachepod
      ports:
        - containerPort: 80
      resources: {}
      volumeMounts:
        - name: config-volume
          mountPath: /site/
  volumes:
    - name: config-volume
      configMap:
        name: apache-config
status: {}
