apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysqlcnf
data:
  image: larian147/mysqlimg:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: larian147/mysqlimg:latest
